# ???? - Maven?????????
plugin.name=${plugin.name}
plugin.package.prefix=${plugin.package.prefix}
netty.port=${netty.port}
context.menu.name=${context.menu.name}

# ????
switch.jsonlister.enabled=${switch.jsonlister.enabled}
switch.routefuzzer.enabled=${switch.routefuzzer.enabled}
switch.paramfuzzer.enabled=${switch.paramfuzzer.enabled}
switch.paramdeleter.enabled=${switch.paramdeleter.enabled}
switch.paramadder.enabled=${switch.paramadder.enabled}
switch.paramcollector.enabled=${switch.paramcollector.enabled}
switch.headerfuzzer.enabled=${switch.headerfuzzer.enabled}
switch.cookiefuzzer.enabled=${switch.cookiefuzzer.enabled}
switch.oobparamfuzzer.enabled=${switch.oobparamfuzzer.enabled}